services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mental_health_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mental_health_db}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mental-health-network
    command: --default-authentication-plugin=mysql_native_password --skip-ssl --disable-ssl
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-rootpassword}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mental_health_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"
    networks:
      - mental-health-network

  # Backend server (Node.js/Express)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mental_health_backend
    restart: on-failure:3  # Limit restart attempts to prevent infinite restart loops
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-4000}
      - DB_USERNAME=${DB_USERNAME:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-mental_health_db}
      - DB_HOST=mysql
      - DB_DIALECT=mysql
      - JWT_SECRET=${JWT_SECRET:-YourSuperSecretKeyForJWT}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: >
      sh -c "
        echo 'Installing dependencies...' &&
        npm install &&
        echo 'Waiting for MySQL to be ready...' &&
        sleep 15 &&
        echo 'Checking MySQL connection...' &&
        echo 'DB_HOST: $DB_HOST' &&
        echo 'DB_USERNAME: $DB_USERNAME' &&
        echo 'DB_NAME: $DB_NAME' &&
        echo 'Checking for MariaDB client...' &&
        which mariadb || echo 'MariaDB client not found' &&
        mariadb --version || echo 'MariaDB client version failed' &&
        echo 'Running database setup...' &&
        npm run db:demo-setup &&
        echo 'Starting server...' &&
        npm run dev
      "
    networks:
      - mental-health-network

  # Frontend (React)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mental_health_frontend
    restart: always
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:4000}
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm start
    networks:
      - mental-health-network

volumes:
  mysql_data:

networks:
  mental-health-network:
    driver: bridge 